// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Preqin.Infrastructure.Data;

#nullable disable

namespace Preqin.Infrastructure.Migrations
{
    [DbContext(typeof(PreqinDbContext))]
    partial class PreqinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Preqin.Domain.Commitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestorId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.HasIndex("InvestorId1");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("Preqin.Domain.Investor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvestorCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorDateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvestorLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("Preqin.Domain.Commitment", b =>
                {
                    b.HasOne("Preqin.Domain.Investor", null)
                        .WithMany("Commitments")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Preqin.Domain.Investor", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Preqin.Domain.Investor", b =>
                {
                    b.Navigation("Commitments");
                });
#pragma warning restore 612, 618
        }
    }
}
